# Instructions: https://certbot-dns-azure.readthedocs.io/en/latest/

# System Assigned Azure Managed Identity
dns_azure_msi_system_assigned = true
dns_azure_environment = "AzurePublicCloud"
#dns_azure_zone1 = $!{{PRIMARY_DOMAIN}}:/subscriptions/$!{{AZURE_SUBSCRIPTION_ID}}/resourceGroups/$!{{AZURE_RESOURCE_GROUP}}
dns_azure_zone1 = $!{{PRIMARY_DOMAIN}}:$!{{AZURE_RESOURCE_GROUP}}
